name: Preprocessing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn matplotlib seaborn

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Muhammad_Fauza.py

      - name: Commit processed file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/landmine_preprocessing.csv
          git commit -m "Update processed dataset via GitHub Actions" || echo "No changes to commit"
          git push
